---
- hosts: icinga-devops-01 icinga-devops-02
  roles:
   - role: environment
     become: yes

   - role: icinga2
     icinga2_conf_global: |
       include "constants.conf"
       include "zones.conf"
       include <itl>
       include <plugins>
       include "features-enabled/*.conf"
       include_recursive "conf.d"
     check_commands:
       check_nrpe: |
          "-H", "$address$",
              "-c", "$remote_nrpe_command$",
  tags: icinga2-no-ui
