---
# Wrote by Hoang Anh Tu
  - stat: path=/var/tmp/git-2.9.5
    register: git_temp_path

  - name: ICINGA2-UI [STEP 01] - Download and Extract Git-2.9.5
    command: chdir=/var/tmp/ {{ item }}
    with_items: 
      - wget https://www.kernel.org/pub/software/scm/git/git-2.9.5.tar.gz
      - tar -xvzf git-2.9.5.tar.gz
      - chmod -R 775 git-2.9.5
    when: 
      - git_temp_path.stat.exists == false
      - ui_node == "on"

  - name: ICINGA2-UI [STEP 02] - Compile and Install Git-2.9.5
    command: chdir=/var/tmp/git-2.9.5 {{ item }}
    with_items: 
      - ./configure
      - make
      - make install
    when: 
      - git_temp_path.stat.exists == false
      - ui_node == "on"

  - stat: path=/etc/icinga2-ui
    register: icinga2_ui_path

  - name: ICINGA2-UI [STEP 03] - Creates Icinga2-ui's directory (Only on UI Node)
    file: path={{ item }} state=directory
    with_items:
      - /etc/icinga2-ui
      - /etc/icinga2-ui/dist
    when: 
      - icinga2_ui_path.stat.exists == false
      - ui_node == "on"

  - name: ICINGA2-UI [Step 04] - Install Icinga2-ui (Only on UI Node)
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0775
    with_items:
      - { src: "{{ role_path }}/files/icinga2-ui/icinga2-ui", dest: "/etc/icinga2-ui/dist/" }
      - { src: "{{ role_path }}/files/icinga2-ui/icinga2-ui.service", dest: "/etc/systemd/system/" }
    when: 
      - icinga2_ui_path.stat.exists == false
      - ui_node == "on"

  - stat: "path=/etc/icinga2-ui/demo_config"
    register: icinga2_ui_demo_path

  - name: ICINGA2-UI [Step 05] - Copy Icinga2-ui's Demo configure (Only on UI Node)
    copy: 
      src: "{{ role_path }}/files/demo_icinga_config/"
      dest: "/etc/icinga2-ui/demo_config"
      owner: root
      group: root
      mode: 0775
    when:
      - icinga2_ui_demo_path.stat.exists == false
      - ui_node == "on"

  - stat: path=/etc/icinga2-ui/{{ item }}
    with_items:
      - "{{ ui_node_ip }}"
    register: icinga2_ui_node_path
    when:
      - ui_node == "on"

  - name: ICINGA2-UI [Step 06] - Create Icinga2-ui's Node configure (Only on UI Node)
    shell: cp -rf /etc/icinga2-ui/demo_config /etc/icinga2-ui/{{ item }}
    with_items:
      - "{{ all_node_ip }}"
    when: 
      - ui_node == "on"

  - name: ICINGA2-UI [Step 07] - Reload Systemctl
    command: systemctl daemon-reload
    when: 
      - ui_node == "on"

  - name: ICINGA2-UI [Step 08] - Startup Icinga2-ui
    service: name=icinga2-ui
             state=restarted
             enabled=yes
    when:
      - ui_node == "on"

  - name: ICINGA2-UI [Step 09] - Add Known_hosts (Only on UI Node)
    shell: ssh-keyscan -H {{ item }} > /etc/ssh/ssh_known_hosts
    with_items:
      - "{{ all_node_ip }}"
    when: 
      - ui_node == "on"
